version: '3.8'

services:
  # Frontend (Angular with SSR)
  ui:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - CONFIGURATION=${NODE_ENV:-production}
    container_name: order_management_ui
    restart: always
    ports:
      - "${UI_PORT:-80}:80"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - API_URL=${API_URL:-http://localhost:3000}
      - PORT=80
    networks:
      - order_management_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  order_management_network:
    name: order_management_network